---
name: Docs 📚

on:
  push:
    branches:
      - main
    paths:
      - inst/templates/**
      - _pkgdown.yml
      - DESCRIPTION
      - '**.md'
      - man/**
      - LICENSE.*
      - NAMESPACE
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - pre-release
    paths:
      - inst/templates/**
      - _pkgdown.yml
      - DESCRIPTION
      - '**.md'
      - man/**
      - LICENSE.*
      - NAMESPACE
  workflow_dispatch:

jobs:
  docs:
    name: Pkgdown Docs 📚 
    uses: insightsengineering/r.pkg.template/.github/workflows/pkgdown.yaml@302_man_page_update
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      update: true
